# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '007-系列转场动画01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry'

  # Pods for 007-系列转场动画01

end
